#!/bin/bash
set -e

if [ "$VERBOSE" = "1" ];
then
  set -x
fi

# FIXME: walk up the directory structure to find a ".plank" directory
export PLANK_ROOT=.plank
export PLANK_JAR=dist/plank.jar


dl="wget"
clj_version="1.5.1"
clj_dl=http://repo1.maven.org/maven2/org/clojure/clojure/$clj_version/clojure-$clj_version.zip
export CLOJURE_JAR=$PLANK_ROOT/lib/clojure-$clj_version.jar
java=java

if [ ! -f "$CLOJURE_JAR" ];
then
  (
    mkdir -p $PLANK_ROOT
    cd $PLANK_ROOT
    mkdir build
    cd build
    $dl $clj_dl
    unzip clojure-$clj_version.zip
    mkdir -p $(dirname $CLOJURE_JAR)
    mv clojure-$clj_version/clojure-$clj_version.jar $CLOJURE_JAR
    rm -rf build
  )
fi

$java -cp $CLOJURE_JAR clojure.main plank.clj $@

